version = 0.1

[dev.deploy.parameters]
stack_name = "sam-app-Qubeyond"
s3_bucket = "Qubeyond-bucket-name"
s3_prefix = "sam-app-Qubeyond"
region = "ap-south-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"dev\" Region=\"ap-south-1\" APIName=\"qubeyondapi\""
image_repositories = []



